#!/bin/bash

#!————————————————————————————————————————————————————————————————————————————*!
# Git pre-commit hook.
#
# Run `make setup-hooks` to install.
#!————————————————————————————————————————————————————————————————————————————*!

echo "running pre-commit hook..."

# Format files.
make clean