#!————————————————————————————————————————————————————————————————————————————*!
# GitHub action for continuous integration. Triggered on pull requests into
# the main branch and commits on the main branch.
#
# Currently, this action executes the following:
#   - Ensure that formatting is correct (no changes when `make clean` is ran)
#   - Runs unit tests
#
#!————————————————————————————————————————————————————————————————————————————*!

name: CI                           # workflow name

on:
  push:
    branches: [ main ]  # Activate on commits to main.
  pull_request:
    branches: [ main ]  # Activate on pull requests.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    # Checkout the source code of the project.

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: formatting             # Ensure formatting is correct.
      run: |
        make clean
        git diff --exit-code

    - name: unit tests             # Run unit tests.
      run: go test -v ./...